package cn.nukkit.utils;

import cn.nukkit.block.Block;
import cn.nukkit.entity.Entity;
import cn.nukkit.item.Item;
//import cn.nukkit.level.particle.Particle;
import com.google.common.collect.ImmutableBiMap;

public class Identifier {

    public static final String PREFIX = "minecraft:";

    private static final ImmutableBiMap<String, Integer> BLOCK_IDENTIFIER = ImmutableBiMap.<String, Integer>builder()
            .put("air", Block.AIR)
            .put("stone", Block.STONE)
            .put("grass", Block.GRASS)
            .put("dirt", Block.DIRT)
            .put("cobblestone", Block.COBBLESTONE)
            .put("planks", Block.PLANK)
            .put("sapling", Block.SAPLING)
            .put("bedrock", Block.BEDROCK)
            .put("flowing_water", Block.WATER)
            .put("water", Block.STILL_WATER)
            .put("flowing_lava", Block.LAVA)
            .put("lava", Block.STILL_LAVA)
            .put("sand", Block.SAND)
            .put("gravel", Block.GRAVEL)
            .put("gold_ore", Block.GOLD_ORE)
            .put("iron_ore", Block.IRON_ORE)
            .put("coal_ore", Block.COAL_ORE)
            .put("log", Block.LOG)
            .put("leaves", Block.LEAVES)
            .put("sponge", Block.SPONGE)
            .put("glass", Block.GLASS)
            .put("lapis_ore", Block.LAPIS_ORE)
            .put("lapis_block", Block.LAPIS_BLOCK)
            .put("dispenser", Block.DISPENSER)
            .put("sandstone", Block.SANDSTONE)
            .put("noteblock", Block.NOTEBLOCK)
            .put("bed", Block.BED_BLOCK)
            .put("golden_rail", Block.POWERED_RAIL)
            .put("detector_rail", Block.DETECTOR_RAIL)
            .put("sticky_piston", Block.STICKY_PISTON)
            .put("web", Block.COBWEB)
            .put("tallgrass", Block.TALL_GRASS)
            .put("deadbush", Block.BUSH)
            .put("piston", Block.PISTON)
            .put("pistonArmCollision", Block.PISTON_HEAD)
            .put("wool", Block.WOOL)
            .put("element_0", Block.ELEMENT_0)
            .put("yellow_flower", Block.DANDELION)
            .put("red_flower", Block.POPPY)
            .put("brown_mushroom", Block.BROWN_MUSHROOM)
            .put("red_mushroom", Block.RED_MUSHROOM)
            .put("gold_block", Block.GOLD_BLOCK)
            .put("iron_block", Block.IRON_BLOCK)
            .put("double_stone_slab", Block.DOUBLE_SLAB)
            .put("stone_slab", Block.SLAB)
            .put("brick_block", Block.BRICKS)
            .put("tnt", Block.TNT)
            .put("bookshelf", Block.BOOKSHELF)
            .put("mossy_cobblestone", Block.MOSS_STONE)
            .put("obsidian", Block.OBSIDIAN)
            .put("torch", Block.TORCH)
            .put("fire", Block.FIRE)
            .put("mob_spawner", Block.MONSTER_SPAWNER)
            .put("oak_stairs", Block.WOOD_STAIRS)
            .put("chest", Block.CHEST)
            .put("redstone_wire", Block.REDSTONE_WIRE)
            .put("diamond_ore", Block.DIAMOND_ORE)
            .put("diamond_block", Block.DIAMOND_BLOCK)
            .put("crafting_table", Block.CRAFTING_TABLE)
            .put("wheat", Block.WHEAT_BLOCK)
            .put("farmland", Block.FARMLAND)
            .put("furnace", Block.FURNACE)
            .put("lit_furnace", Block.BURNING_FURNACE)
            .put("standing_sign", Block.SIGN_POST)
            .put("wooden_door", Block.DOOR_BLOCK)
            .put("ladder", Block.LADDER)
            .put("rail", Block.RAIL)
            .put("stone_stairs", Block.COBBLE_STAIRS)
            .put("wall_sign", Block.WALL_SIGN)
            .put("lever", Block.LEVER)
            .put("stone_pressure_plate", Block.STONE_PRESSURE_PLATE)
            .put("iron_door", Block.IRON_DOOR_BLOCK)
            .put("wooden_pressure_plate", Block.WOODEN_PRESSURE_PLATE)
            .put("redstone_ore", Block.REDSTONE_ORE)
            .put("lit_redstone_ore", Block.GLOWING_REDSTONE_ORE)
            .put("unlit_redstone_torch", Block.UNLIT_REDSTONE_TORCH)
            .put("redstone_torch", Block.REDSTONE_TORCH)
            .put("stone_button", Block.STONE_BUTTON)
            .put("snow_layer", Block.SNOW)
            .put("ice", Block.ICE)
            .put("snow", Block.SNOW_BLOCK)
            .put("cactus", Block.CACTUS)
            .put("clay", Block.CLAY_BLOCK)
            .put("reeds", Block.REEDS)
            .put("jukebox", Block.JUKEBOX)
            .put("fence", Block.FENCE)
            .put("pumpkin", Block.PUMPKIN)
            .put("netherrack", Block.NETHERRACK)
            .put("soul_sand", Block.SOUL_SAND)
            .put("glowstone", Block.GLOWSTONE)
            .put("portal", Block.NETHER_PORTAL)
            .put("lit_pumpkin", Block.LIT_PUMPKIN)
            .put("cake", Block.CAKE_BLOCK)
            .put("unpowered_repeater", Block.UNPOWERED_REPEATER)
            .put("powered_repeater", Block.POWERED_REPEATER)
            .put("invisibleBedrock", Block.INVISIBLE_BEDROCK)
            .put("trapdoor", Block.TRAPDOOR)
            .put("monster_egg", Block.MONSTER_EGG)
            .put("stonebrick", Block.STONE_BRICKS)
            .put("brown_mushroom_block", Block.BROWN_MUSHROOM_BLOCK)
            .put("red_mushroom_block", Block.RED_MUSHROOM_BLOCK)
            .put("iron_bars", Block.IRON_BAR)
            .put("glass_pane", Block.GLASS_PANE)
            .put("melon_block", Block.MELON_BLOCK)
            .put("pumpkin_stem", Block.PUMPKIN_STEM)
            .put("melon_stem", Block.MELON_STEM)
            .put("vine", Block.VINE)
            .put("fence_gate", Block.FENCE_GATE)
            .put("brick_stairs", Block.BRICK_STAIRS)
            .put("stone_brick_stairs", Block.STONE_BRICK_STAIRS)
            .put("mycelium", Block.MYCELIUM)
            .put("waterlily", Block.WATER_LILY)
            .put("nether_brick", Block.NETHER_BRICKS)
            .put("nether_brick_fence", Block.NETHER_BRICK_FENCE)
            .put("nether_brick_stairs", Block.NETHER_BRICKS_STAIRS)
            .put("nether_wart", Block.NETHER_WART_BLOCK)
            .put("enchanting_table", Block.ENCHANTING_TABLE)
            .put("brewing_stand", Block.BREWING_STAND_BLOCK)
            .put("cauldron", Block.CAULDRON_BLOCK)
            .put("end_portal", Block.END_PORTAL)
            .put("end_portal_frame", Block.END_PORTAL_FRAME)
            .put("end_stone", Block.END_STONE)
            .put("dragon_egg", Block.DRAGON_EGG)
            .put("redstone_lamp", Block.REDSTONE_LAMP)
            .put("lit_redstone_lamp", Block.LIT_REDSTONE_LAMP)
            .put("dropper", Block.DROPPER)
            .put("activator_rail", Block.ACTIVATOR_RAIL)
            .put("cocoa", Block.COCOA)
            .put("sandstone_stairs", Block.SANDSTONE_STAIRS)
            .put("emerald_ore", Block.EMERALD_ORE)
            .put("ender_chest", Block.ENDER_CHEST)
            .put("tripwire_hook", Block.TRIPWIRE_HOOK)
            .put("tripWire", Block.TRIPWIRE)
            .put("emerald_block", Block.EMERALD_BLOCK)
            .put("spruce_stairs", Block.SPRUCE_WOOD_STAIRS)
            .put("birch_stairs", Block.BIRCH_WOOD_STAIRS)
            .put("jungle_stairs", Block.JUNGLE_WOOD_STAIRS)
            .put("command_block", Block.COMMAND_BLOCK)
            .put("beacon", Block.BEACON)
            .put("cobblestone_wall", Block.COBBLE_WALL)
            .put("flower_pot", Block.FLOWER_POT_BLOCK)
            .put("carrots", Block.CARROT_BLOCK)
            .put("potatoes", Block.POTATO_BLOCK)
            .put("wooden_button", Block.WOODEN_BUTTON)
            .put("skull", Block.SKULL_BLOCK)
            .put("anvil", Block.ANVIL)
            .put("trapped_chest", Block.TRAPPED_CHEST)
            .put("light_weighted_pressure_plate", Block.LIGHT_WEIGHTED_PRESSURE_PLATE)
            .put("heavy_weighted_pressure_plate", Block.HEAVY_WEIGHTED_PRESSURE_PLATE)
            .put("unpowered_comparator", Block.UNPOWERED_COMPARATOR)
            .put("powered_comparator", Block.POWERED_COMPARATOR)
            .put("daylight_detector", Block.DAYLIGHT_DETECTOR)
            .put("redstone_block", Block.REDSTONE_BLOCK)
            .put("quartz_ore", Block.QUARTZ_ORE)
            .put("hopper", Block.HOPPER_BLOCK)
            .put("quartz_block", Block.QUARTZ_BLOCK)
            .put("quartz_stairs", Block.QUARTZ_STAIRS)
            .put("double_wooden_slab", Block.DOUBLE_WOOD_SLAB)
            .put("wooden_slab", Block.WOOD_SLAB)
            .put("stained_hardened_clay", Block.STAINED_TERRACOTTA)
            .put("stained_glass_pane", Block.STAINED_GLASS_PANE)
            .put("leaves2", Block.LEAVES2)
            .put("log2", Block.WOOD2)
            .put("acacia_stairs", Block.ACACIA_WOOD_STAIRS)
            .put("dark_oak_stairs", Block.DARK_OAK_WOOD_STAIRS)
            .put("slime", Block.SLIME_BLOCK)
            //166 edu
            .put("iron_trapdoor", Block.IRON_TRAPDOOR)
            .put("prismarine", Block.PRISMARINE)
            .put("seaLantern", Block.SEA_LANTERN)
            .put("hay_block", Block.HAY_BALE)
            .put("carpet", Block.CARPET)
            .put("hardened_clay", Block.TERRACOTTA)
            .put("coal_block", Block.COAL_BLOCK)
            .put("packed_ice", Block.PACKED_ICE)
            .put("double_plant", Block.DOUBLE_PLANT)
            .put("standing_banner", Block.STANDING_BANNER)
            .put("wall_banner", Block.WALL_BANNER)
            .put("daylight_detector_inverted", Block.DAYLIGHT_DETECTOR_INVERTED)
            .put("red_sandstone", Block.RED_SANDSTONE)
            .put("red_sandstone_stairs", Block.RED_SANDSTONE_STAIRS)
            .put("double_stone_slab2", Block.DOUBLE_RED_SANDSTONE_SLAB)
            .put("stone_slab2", Block.RED_SANDSTONE_SLAB)
            .put("spruce_fence_gate", Block.FENCE_GATE_SPRUCE)
            .put("birch_fence_gate", Block.FENCE_GATE_BIRCH)
            .put("jungle_fence_gate", Block.FENCE_GATE_JUNGLE)
            .put("dark_oak_fence_gate", Block.FENCE_GATE_DARK_OAK)
            .put("acacia_fence_gate", Block.FENCE_GATE_ACACIA)
            .put("repeating_command_block", Block.REPEATING_COMMAND_BLOCK)
            .put("chain_command_block", Block.CHAIN_COMMAND_BLOCK)
            //.put("hard_glass_pane", Block.190)
            //.put("hard_stained_glass_pane", Block.191)
            //.put("chemical_heat", Block.192)
            .put("spruce_door", Block.SPRUCE_DOOR_BLOCK)
            .put("birch_door", Block.BIRCH_DOOR_BLOCK)
            .put("jungle_door", Block.JUNGLE_DOOR_BLOCK)
            .put("acacia_door", Block.ACACIA_DOOR_BLOCK)
            .put("dark_oak_door", Block.DARK_OAK_DOOR_BLOCK)
            .put("grass_path", Block.GRASS_PATH)
            .put("frame", Block.ITEM_FRAME_BLOCK)
            .put("chorus_flower", Block.CHORUS_FLOWER)
            .put("purpur_block", Block.PURPUR_BLOCK)
            //.put("colored_torch_rg", Block.202)
            .put("purpur_stairs", Block.PURPUR_STAIRS)
            //.put("colored_torch_bp", Block.204)
            .put("undyed_shulker_box", Block.UNDYED_SHULKER_BOX)
            .put("end_bricks", Block.END_BRICKS)
            .put("frosted_ice", Block.FROSTED_ICE)
            .put("end_rod", Block.END_ROD)
            .put("end_gateway", Block.END_GATEWAY)

            .put("magma", Block.MAGMA)
            .put("nether_wart_block", Block.BLOCK_NETHER_WART_BLOCK)
            .put("red_nether_brick", Block.RED_NETHER_BRICK)
            .put("bone_block", Block.BONE_BLOCK)

            .put("shulker_box", Block.SHULKER_BOX)
            .put("purple_glazed_terracotta", Block.PURPLE_GLAZED_TERRACOTTA)
            .put("white_glazed_terracotta", Block.WHITE_GLAZED_TERRACOTTA)
            .put("orange_glazed_terracotta", Block.ORANGE_GLAZED_TERRACOTTA)
            .put("magenta_glazed_terracotta", Block.MAGENTA_GLAZED_TERRACOTTA)
            .put("light_blue_glazed_terracotta", Block.LIGHT_BLUE_GLAZED_TERRACOTTA)
            .put("yellow_glazed_terracotta", Block.YELLOW_GLAZED_TERRACOTTA)
            .put("lime_glazed_terracotta", Block.LIME_GLAZED_TERRACOTTA)
            .put("pink_glazed_terracotta", Block.PINK_GLAZED_TERRACOTTA)
            .put("gray_glazed_terracotta", Block.GRAY_GLAZED_TERRACOTTA)
            .put("silver_glazed_terracotta", Block.SILVER_GLAZED_TERRACOTTA)
            .put("cyan_glazed_terracotta", Block.CYAN_GLAZED_TERRACOTTA)
            .put("blue_glazed_terracotta", Block.BLUE_GLAZED_TERRACOTTA)
            .put("brown_glazed_terracotta", Block.BROWN_GLAZED_TERRACOTTA)
            .put("green_glazed_terracotta", Block.GREEN_GLAZED_TERRACOTTA)
            .put("red_glazed_terracotta", Block.RED_GLAZED_TERRACOTTA)
            .put("black_glazed_terracotta", Block.BLACK_GLAZED_TERRACOTTA)
            .put("concrete", Block.CONCRETE)
            .put("concretePowder", Block.CONCRETE_POWDER)
            //.put("chemistry_table", Block.238)
            //.put("underwater_torch", Block.239)
            .put("chorus_plant", Block.CHORUS_PLANT)
            .put("stained_glass", Block.STAINED_GLASS)

            .put("podzol", Block.PODZOL)
            .put("beetroot", Block.BEETROOT_BLOCK)
            .put("stonecutter", Block.STONECUTTER)
            .put("glowingobsidian", Block.GLOWING_OBSIDIAN)
            .put("netherreactor", Block.NETHER_REACTOR_CORE)
            //.put("info_update", Block.248)
            //.put("info_update2", Block.249)
            .put("movingBlock", Block.MOVING_BLOCK)
            .put("observer", Block.OBSERVER)
            .put("structure_block", Block.STRUCTURE_BLOCK)
            //.put("hard_glass", Block.253)
            //.put("hard_stained_glass", Block.254)
            //.put("reserved6", Block.255)
            .put("prismarine_stairs", Block.PRISMARINE_STAIRS)
            .put("dark_prismarine_stairs", Block.DARK_PRISMARINE_STAIRS)
            .put("prismarine_bricks_stairs", Block.PRISMARINE_BRICKS_STAIRS)
            .put("stripped_spruce_log", Block.STRIPPED_SPRUCE_LOG)
            .put("stripped_birch_log", Block.STRIPPED_BIRCH_LOG)
            .put("stripped_jungle_log", Block.STRIPPED_JUNGLE_LOG)
            .put("stripped_acacia_log", Block.STRIPPED_ACACIA_LOG)
            .put("stripped_dark_oak_log", Block.STRIPPED_DARK_OAK_LOG)
            .put("stripped_oak_log", Block.STRIPPED_OAK_LOG)
            .put("blue_ice", Block.BLUE_ICE)
            /*
            .put("element_1", Block.267)
            .put("element_2", Block.268)
            .put("element_3", Block.279)
            .put("element_4", Block.270)
            .put("element_5", Block.271)
            .put("element_6", Block.272)
            .put("element_7", Block.273)
            .put("element_8", Block.274)
            .put("element_9", Block.275)
            .put("element_10", Block.276)
            .put("element_11", Block.277)
            .put("element_12", Block.278)
            .put("element_13", Block.289)
            .put("element_14", Block.280)
            .put("element_15", Block.281)
            .put("element_16", Block.282)
            .put("element_17", Block.283)
            .put("element_18", Block.284)
            .put("element_19", Block.285)
            .put("element_20", Block.286)
            .put("element_21", Block.287)
            .put("element_22", Block.288)
            .put("element_23", Block.299)
            .put("element_24", Block.290)
            .put("element_25", Block.291)
            .put("element_26", Block.292)
            .put("element_27", Block.293)
            .put("element_28", Block.294)
            .put("element_29", Block.295)
            .put("element_30", Block.296)
            .put("element_31", Block.298)
            .put("element_32", Block.299)
            .put("element_33", Block.300)
            .put("element_34", Block.301)
            .put("element_35", Block.302)
            .put("element_36", Block.303)
            .put("element_37", Block.304)
            .put("element_38", Block.305)
            .put("element_39", Block.306)
            .put("element_40", Block.307)
            .put("element_41", Block.308)
            .put("element_42", Block.309)
            .put("element_43", Block.310)
            .put("element_44", Block.311)
            .put("element_45", Block.312)
            .put("element_46", Block.313)
            .put("element_47", Block.314)
            .put("element_48", Block.315)
            .put("element_49", Block.316)
            .put("element_50", Block.317)
            .put("element_51", Block.318)
            .put("element_52", Block.319)
            .put("element_53", Block.320)
            .put("element_54", Block.321)
            .put("element_55", Block.322)
            .put("element_56", Block.323)
            .put("element_57", Block.324)
            .put("element_58", Block.325)
            .put("element_59", Block.326)
            .put("element_60", Block.327)
            .put("element_61", Block.328)
            .put("element_62", Block.329)
            .put("element_63", Block.330)
            .put("element_64", Block.331)
            .put("element_65", Block.332)
            .put("element_66", Block.333)
            .put("element_67", Block.334)
            .put("element_68", Block.335)
            .put("element_69", Block.335)
            .put("element_70", Block.336)
            .put("element_71", Block.337)
            .put("element_72", Block.338)
            .put("element_73", Block.339)
            .put("element_74", Block.340)
            .put("element_75", Block.341)
            .put("element_76", Block.342)
            .put("element_77", Block.343)
            .put("element_78", Block.344)
            .put("element_79", Block.345)
            .put("element_80", Block.346)
            .put("element_81", Block.347)
            .put("element_82", Block.348)
            .put("element_83", Block.349)
            .put("element_84", Block.350)
            .put("element_85", Block.351)
            .put("element_86", Block.352)
            .put("element_87", Block.353)
            .put("element_88", Block.354)
            .put("element_89", Block.355)
            .put("element_90", Block.356)
            .put("element_91", Block.357)
            .put("element_92", Block.358)
            .put("element_93", Block.359)
            .put("element_94", Block.360)
            .put("element_95", Block.361)
            .put("element_96", Block.362)
            .put("element_97", Block.363)
            .put("element_98", Block.364)
            .put("element_99", Block.365)
            .put("element_100", Block.366)
            .put("element_101", Block.367)
            .put("element_102", Block.368)
            .put("element_103", Block.369)
            .put("element_104", Block.370)
            .put("element_105", Block.371)
            .put("element_106", Block.372)
            .put("element_108", Block.374)
            .put("element_109", Block.375)
            .put("element_110", Block.376)
            .put("element_111", Block.377)
            .put("element_112", Block.378)
            .put("element_113", Block.379)
            .put("element_114", Block.380)
            .put("element_115", Block.381)
            .put("element_116", Block.382)
            .put("element_117", Block.383)
            .put("element_118", Block.384)
            */
            .put("seagrass", Block.SEAGRASS)
            .put("coral", Block.CORAL)
            .put("coral_block", Block.CORAL_BLOCK)
            .put("coral_fan", Block.CORAL_FAN)
            .put("coral_fan_dead", Block.DEAD_CORAL_FAN)
            .put("coral_fan_hang", Block.CORAL_FAN_HANG)
            .put("coral_fan_hang2", Block.CORAL_FAN_HANG2)
            .put("coral_fan_hang3", Block.CORAL_FAN_HANG3)
            .put("kelp", Block.KELP_BLOCK)
            .put("dried_kelp_block", Block.DRIED_KELP_BLOCK)
            .put("acacia_button", Block.ACACIA_BUTTON)
            .put("birch_button", Block.BIRCH_BUTTON)
            .put("dark_oak_button", Block.DARK_OAK_BUTTON)
            .put("jungle_button", Block.JUNGLE_BUTTON)
            .put("spruce_button", Block.SPRUCE_BUTTON)
            .put("acacia_trapdoor", Block.ACACIA_TRAPDOOR)
            .put("birch_trapdoor", Block.BIRCH_TRAPDOOR)
            .put("dark_oak_trapdoor", Block.DARK_OAK_TRAPDOOR)
            .put("jungle_trapdoor", Block.JUNGLE_TRAPDOOR)
            .put("spruce_trapdoor", Block.SPRUCE_TRAPDOOR)
            .put("acacia_pressure_plate", Block.ACACIA_PRESSURE_PLATE)
            .put("birch_pressure_plate", Block.BIRCH_PRESSURE_PLATE)
            .put("dark_oak_pressure_plate", Block.DARK_OAK_PRESSURE_PLATE)
            .put("jungle_pressure_plate", Block.JUNGLE_PRESSURE_PLATE)
            .put("spruce_pressure_plate", Block.SPRUCE_PRESSURE_PLATE)
            .put("carved_pumpkin", Block.CARVED_PUMPKIN)
            .put("sea_pickle", Block.SEA_PICKLE)
            .put("conduit", Block.CONDUIT)

            .put("turtle_egg", Block.TURTLE_EGG)
            .put("bubble_column", Block.BUBBLE_COLUMN)
            .put("barrier", Block.BARRIER)
            //.put("bamboo", Block.417)
            .put("bamboo_sapling", Block.BAMBOO)
            .put("scaffolding", Block.BAMBOO_SAPLING)
            .put("smooth_stone", Block.SCAFFOLDING)
            /*
            .put("spruce_standing_sign", Block.421)
            .put("diorite_stairs", Block.422)
            .put("darkoak_standing_sign", Block.423)
            .put("double_stone_slab4", Block.424)
            .put("stone_slab4", Block.425)
            .put("acacia_standing_sign", Block.426)
            .put("polished_diorite_stairs", Block.427)
            .put("birch_standing_sign", Block.428)
            .put("mossy_stone_brick_stairs", Block.429)
            .put("polished_granite_stairs", Block.430)
            .put("stone_slab3", Block.431)
            .put("double_stone_slab3", Block.432)
            .put("end_brick_stairs", Block.433)
            .put("birch_wall_sign", Block.434)
            .put("red_nether_brick_stairs", Block.435)
            .put("acacia_wall_sign", Block.436)
            .put("polished_andesite_stairs", Block.437)
            .put("normal_stone_stairs", Block.438)
            .put("granite_stairs", Block.439)
            .put("mossy_cobblestone_stairs", Block.440)
            .put("smooth_sandstone_stairs", Block.441)
            .put("smooth_quartz_stairs", Block.442)
            .put("jungle_standing_sign", Block.443)
            .put("darkoak_wall_sign", Block.444)
            .put("jungle_wall_sign", Block.445)
            .put("andesite_stairs", Block.446)
            .put("smooth_red_sandstone_stairs", Block.447)
            .put("spruce_wall_sign", Block.448)
            .put("lava_cauldron", Block.449)
            .put("smoker", Block.450)
            .put("blast_furnace", Block.451)
            .put("fletching_table", Block.452)
            .put("barrel", Block.453)
            .put("grindstone", Block.454)
            .put("lantern", Block.455)
            .put("bell", Block.456)
            .put("cartography_table", Block.457)
            .put("smithing_table", Block.458)
            */
            .build();

    private static final ImmutableBiMap<String, Integer> ITEM_IDENTIFIER = ImmutableBiMap.<String, Integer>builder()
            .put("iron_shovel", Item.IRON_SHOVEL)
            .put("iron_pickaxe", Item.IRON_PICKAXE)
            .put("iron_axe", Item.IRON_AXE)
            .put("flint_and_steel", Item.FLINT_AND_STEEL)
            .put("apple", Item.APPLE)
            .put("bow", Item.BOW)
            .put("arrow", Item.ARROW)
            .put("coal", Item.COAL)
            .put("diamond", Item.DIAMOND)
            .put("iron_ingot", Item.IRON_INGOT)
            .put("gold_ingot", Item.GOLD_INGOT)
            .put("iron_sword", Item.IRON_SWORD)
            .put("wooden_sword", Item.WOODEN_SWORD)
            .put("wooden_shovel", Item.WOODEN_SHOVEL)
            .put("wooden_pickaxe", Item.WOODEN_PICKAXE)
            .put("wooden_axe	", Item.WOODEN_AXE)
            .put("stone_sword", Item.STONE_SWORD)
            .put("stone_shovel", Item.STONE_SHOVEL)
            .put("stone_pickaxe", Item.STONE_PICKAXE)
            .put("stone_axe", Item.STONE_AXE)
            .put("diamond_sword", Item.DIAMOND_SWORD)
            .put("diamond_shovel", Item.DIAMOND_SHOVEL)
            .put("diamond_pickaxe", Item.DIAMOND_PICKAXE)
            .put("diamond_axe", Item.DIAMOND_AXE)
            .put("stick", Item.STICK)
            .put("bowl", Item.BOWL)
            .put("mushroom_stew", Item.MUSHROOM_STEW)
            .put("golden_sword", Item.GOLDEN_SWORD)
            .put("golden_shovel", Item.GOLDEN_SHOVEL)
            .put("golden_pickaxe", Item.GOLDEN_PICKAXE)
            .put("golden_axe", Item.GOLDEN_AXE)
            .put("string", Item.STRING)
            .put("feather", Item.FEATHER)
            .put("gunpowder", Item.GUNPOWDER)
            .put("wooden_hoe", Item.WOODEN_HOE)
            .put("stone_hoe", Item.STONE_HOE)
            .put("iron_hoe", Item.IRON_HOE)
            .put("diamond_hoe", Item.DIAMOND_HOE)
            .put("golden_hoe", Item.GOLDEN_HOE)
            .put("wheat_seeds", Item.SEEDS)
            .put("wheat", Item.WHEAT)
            .put("bread", Item.BREAD)
            .put("leather_helmet", Item.LEATHER_CAP)
            .put("leather_chestplate", Item.LEATHER_TUNIC)
            .put("leather_leggings", Item.LEATHER_PANTS)
            .put("leather_boots", Item.LEATHER_BOOTS)
            .put("chainmail_helmet", Item.CHAIN_HELMET)
            .put("chainmail_chestplate", Item.CHAIN_CHESTPLATE)
            .put("chainmail_leggings", Item.CHAIN_LEGGINGS)
            .put("chainmail_boots", Item.CHAIN_BOOTS)
            .put("iron_helmet", Item.IRON_HELMET)
            .put("iron_chestplate", Item.IRON_CHESTPLATE)
            .put("iron_leggings", Item.IRON_LEGGINGS)
            .put("iron_boots", Item.IRON_BOOTS)
            .put("diamond_helmet", Item.DIAMOND_HELMET)
            .put("diamond_chestplate", Item.DIAMOND_CHESTPLATE)
            .put("diamond_leggings", Item.DIAMOND_LEGGINGS)
            .put("diamond_boots", Item.DIAMOND_BOOTS)
            .put("golden_helmet", Item.GOLD_HELMET)
            .put("golden_chestplate", Item.GOLD_CHESTPLATE)
            .put("golden_leggings", Item.GOLD_LEGGINGS)
            .put("golden_boots", Item.GOLD_BOOTS)
            .put("flint", Item.FLINT)
            .put("porkchop", Item.RAW_PORKCHOP)
            .put("cooked_porkchop", Item.COOKED_PORKCHOP)
            .put("painting", Item.PAINTING)
            .put("golden_apple", Item.GOLDEN_APPLE)
            .put("sign", Item.SIGN)
            .put("wooden_door", Item.WOODEN_DOOR)
            .put("bucket", Item.BUCKET)
            .put("minecart", Item.MINECART)
            .put("saddle", Item.SADDLE)
            .put("iron_door", Item.IRON_DOOR)
            .put("redstone", Item.REDSTONE)
            .put("snowball", Item.SNOWBALL)
            .put("boat", Item.BOAT)
            .put("leather", Item.LEATHER)
            .put("kelp", Item.KELP)
            .put("brick", Item.BRICK)
            .put("clay_ball", Item.CLAY)
            .put("reeds", Item.SUGAR_CANE)
            .put("paper", Item.PAPER)
            .put("book", Item.BOOK)
            .put("slimeball", Item.SLIMEBALL)
            .put("chest_minecart", Item.MINECART_WITH_CHEST)
            .put("egg", Item.EGG)
            .put("compass", Item.COMPASS)
            .put("fishing_rod", Item.FISHING_ROD)
            .put("clock", Item.CLOCK)
            .put("glowstone_dust", Item.GLOWSTONE_DUST)
            .put("fish", Item.RAW_FISH)
            .put("cooked_fish", Item.COOKED_FISH)
            .put("dye", Item.DYE)
            .put("bone", Item.BONE)
            .put("sugar", Item.SUGAR)
            .put("cake", Item.CAKE)
            .put("bed", Item.BED)
            .put("repeater", Item.REPEATER)
            .put("cookie", Item.COOKIE)
            .put("map_filled", Item.MAP)
            .put("shears", Item.SHEARS)
            .put("melon", Item.MELON)
            .put("pumpkin_seeds", Item.PUMPKIN_SEEDS)
            .put("melon_seeds", Item.MELON_SEEDS)
            .put("beef", Item.RAW_BEEF)
            .put("cooked_beef", Item.COOKED_BEEF)
            .put("chicken", Item.RAW_CHICKEN)
            .put("cooked_chicken", Item.COOKED_CHICKEN)
            .put("rotten_flesh", Item.ROTTEN_FLESH)
            .put("ender_pearl", Item.ENDER_PEARL)
            .put("blaze_rod", Item.BLAZE_ROD)
            .put("ghast_tear", Item.GHAST_TEAR)
            .put("gold_nugget", Item.GOLD_NUGGET)
            .put("nether_wart", Item.NETHER_WART)
            .put("potion", Item.POTION)
            .put("glass_bottle", Item.GLASS_BOTTLE)
            .put("spider_eye", Item.SPIDER_EYE)
            .put("fermented_spider_eye", Item.FERMENTED_SPIDER_EYE)
            .put("blaze_powder", Item.BLAZE_POWDER)
            .put("magma_cream", Item.MAGMA_CREAM)
            .put("brewing_stand", Item.BREWING_STAND)
            .put("cauldron", Item.CAULDRON)
            .put("ender_eye", Item.ENDER_EYE)
            .put("speckled_melon", Item.GLISTERING_MELON)
            .put("spawn_egg", Item.SPAWN_EGG)
            .put("experience_bottle", Item.EXPERIENCE_BOTTLE)
            .put("fireball", Item.FIRE_CHARGE)
            .put("writable_book", Item.BOOK_AND_QUILL)
            .put("written_book", Item.WRITTEN_BOOK)
            .put("emerald", Item.EMERALD)
            .put("frame", Item.ITEM_FRAME)
            .put("frame", Item.FLOWER_POT)
            .put("carrot", Item.CARROT)
            .put("potato", Item.POTATO)
            .put("baked_potato", Item.BAKED_POTATO)
            .put("poisonous_potato", Item.POISONOUS_POTATO)
            .put("emptymap", Item.EMPTY_MAP)
            .put("golden_carrot", Item.GOLDEN_CARROT)
            .put("skull", Item.SKULL)
            .put("carrotonastick", Item.CARROT_ON_A_STICK)
            .put("netherstar", Item.NETHER_STAR)
            .put("pumpkin_pie", Item.PUMPKIN_PIE)
            .put("fireworks", Item.FIREWORKS)
            .put("fireworkscharge", Item.FIREWORKSCHARGE)
            .put("enchanted_book", Item.ENCHANTED_BOOK)
            .put("comparator", Item.COMPARATOR)
            .put("netherbrick", Item.NETHER_BRICK)
            .put("quartz", Item.QUARTZ)
            .put("tnt_minecart", Item.MINECART_WITH_TNT)
            .put("hopper_minecart", Item.MINECART_WITH_HOPPER)
            .put("prismarine_shard", Item.PRISMARINE_SHARD)
            .put("hopper", Item.HOPPER)
            .put("rabbit", Item.RAW_RABBIT)
            .put("cooked_rabbit", Item.COOKED_RABBIT)
            .put("rabbit_stew", Item.RABBIT_STEW)
            .put("rabbit_foot", Item.RABBIT_FOOT)
            .put("rabbit_hide", Item.RABBIT_HIDE)
            .put("horsearmorleather", Item.LEATHER_HORSE_ARMOR)
            .put("horsearmoriron", Item.IRON_HORSE_ARMOR)
            .put("horsearmorgold", Item.GOLD_HORSE_ARMOR)
            .put("horsearmordiamond", Item.DIAMOND_HORSE_ARMOR)
            .put("lead", Item.LEAD)
            .put("nametag", Item.NAME_TAG)
            .put("prismarine_crystals", Item.PRISMARINE_CRYSTALS)
            .put("muttonraw", Item.RAW_MUTTON)
            .put("muttoncooked", Item.COOKED_MUTTON)
            .put("armor_stand", Item.ARMOR_STAND)
            .put("end_crystal", Item.END_CRYSTAL)
            .put("spruce_door", Item.SPRUCE_DOOR)
            .put("birch_door", Item.BIRCH_DOOR)
            .put("jungle_door", Item.JUNGLE_DOOR)
            .put("acacia_door", Item.ACACIA_DOOR)
            .put("dark_oak_door", Item.DARK_OAK_DOOR)
            .put("chorus_fruit", Item.CHORUS_FRUIT)
            .put("chorus_fruit_popped", Item.POPPED_CHORUS_FRUIT)

            .put("dragon_breath", Item.DRAGON_BREATH)
            .put("splash_potion", Item.SPLASH_POTION)

            .put("lingering_potion", Item.LINGERING_POTION)
            .put("sparkler", Item.SPARKLER)
            .put("command_block_minecart", Item.COMMAND_BLOCK_MINECART)
            .put("elytra", Item.ELYTRA)
            .put("shulker_shell", Item.SHULKER_SHELL)
            .put("banner", Item.BANNER)
            .put("eye_drop", Item.EYE_DROP)
            .put("balloon", Item.BALLOON)
            .put("super_fertilizer", Item.SUPER_FERTILIZER)
            .put("totem", Item.TOTEM)
            .put("bleach", Item.BLEACH)
            .put("iron_nugget", Item.IRON_NUGGET)
            .put("ice_bomb", Item.ICE_BOMB)
            //.put("board", Item.CHALKBOARD)
            .put("trident", Item.TRIDENT)
            //.put("portfolio", Item.PORTFOLIO)
            .put("beetroot", Item.BEETROOT)
            .put("beetroot_seeds", Item.BEETROOT_SEEDS)
            .put("beetroot_soup", Item.BEETROOT_SOUP)
            .put("salmon", Item.RAW_SALMON)
            .put("clownfish", Item.CLOWNFISH)
            .put("pufferfish", Item.PUFFERFISH)
            .put("cooked_salmon", Item.COOKED_SALMON)
            .put("dried_kelp", Item.DRIED_KELP)
            .put("nautilus_shell", Item.NAUTILUS_SHELL)
            .put("appleenchanted", Item.GOLDEN_APPLE_ENCHANTED)
            .put("heart_of_the_sea", Item.HEART_OF_THE_SEA)
            .put("turtle_shell_piece", Item.SCUTE)
            .put("turtle_helmet", Item.TURTLE_SHELL)
            .put("phantom_membrane", Item.PHANTOM_MEMBRANE)
            //.put("", Item.CROSSBOW)
            //.put("", Item.SPRUCE_SIGN)
            //.put("", Item.BIRCH_SIGN)
            //.put("", Item.JUNGLE_SIGN)
            //.put("", Item.ACACIA_SIGN)
            //.put("", Item.DARK_OAK_SIGN)
            //.put("camera", Item.CAMERA)
            .put("compound", Item.COMPOUND)
            .put("record_13", Item.RECORD_13)
            .put("record_cat", Item.RECORD_CAT)
            .put("record_blocks", Item.RECORD_BLOCKS)
            .put("record_chirp", Item.RECORD_CHIRP)
            .put("record_far", Item.RECORD_FAR)
            .put("record_mall", Item.RECORD_MALL)
            .put("record_mellohi", Item.RECORD_MELLOHI)
            .put("record_stal", Item.RECORD_STAL)
            .put("record_strad", Item.RECORD_STRAD)
            .put("record_ward", Item.RECORD_WARD)
            .put("record_11", Item.RECORD_11)
            .put("record_wait", Item.RECORD_WAIT)
            .build();

    private static final ImmutableBiMap<String, Integer> ENTITY_IDENTIFIER = ImmutableBiMap.<String, Integer>builder()
            .put("npc", Entity.NPC)
            .put("player", Entity.PLAYER)
            .put("wither_skeleton", Entity.WITHER_SKELETON)
            .put("husk", Entity.HUSK)
            .put("stray", Entity.STRAY)
            .put("witch", Entity.WITCH)
            .put("zombie_villager", Entity.ZOMBIE_VILLAGER)
            .put("blaze", Entity.BLAZE)
            .put("magma_cube", Entity.MAGMA_CUBE)
            .put("ghast", Entity.GHAST)
            .put("cave_spider", Entity.CAVE_SPIDER)
            .put("silverfish", Entity.SILVERFISH)
            .put("enderman", Entity.ENDERMAN)
            .put("slime", Entity.SLIME)
            .put("zombie_pigman", Entity.ZOMBIE_PIGMAN)
            .put("spider", Entity.SPIDER)
            .put("skeleton", Entity.SKELETON)
            .put("creeper", Entity.CREEPER)
            .put("zombie", Entity.ZOMBIE)
            .put("skeleton_horse", Entity.SKELETON_HORSE)
            .put("mule", Entity.MULE)
            .put("donkey", Entity.DONKEY)
            .put("dolphin", Entity.DOLPHIN)
            .put("tropicalfish", Entity.TROPICALFISH)
            .put("wolf", Entity.WOLF)
            .put("squid", Entity.SQUID)
            .put("drowned", Entity.DROWNED)
            .put("sheep", Entity.SHEEP)
            .put("mooshroom", Entity.MOOSHROOM)
            .put("panda", Entity.PANDA)
            .put("salmon", Entity.SALMON)
            .put("pig", Entity.PIG)
            .put("villager", Entity.VILLAGER)
            .put("cod", Entity.COD)
            .put("pufferfish", Entity.PUFFERFISH)
            .put("cow", Entity.COW)
            .put("chicken", Entity.CHICKEN)
            .put("balloon", Entity.BALLOON)
            .put("llama", Entity.LLAMA)
            .put("iron_golem", Entity.IRON_GOLEM)
            .put("rabbit", Entity.RABBIT)
            .put("snow_golem", Entity.SNOW_GOLEM)
            .put("bat", Entity.BAT)
            .put("ocelot", Entity.OCELOT)
            .put("horse", Entity.HORSE)
            .put("cat", Entity.CAT)
            .put("polar_bear", Entity.POLAR_BEAR)
            .put("zombie_horse", Entity.ZOMBIE_HORSE)
            .put("turtle", Entity.TURTLE)
            .put("parrot", Entity.PARROT)
            .put("guardian", Entity.GUARDIAN)
            .put("elder_guardian", Entity.ELDER_GUARDIAN)
            .put("vindicator", Entity.VINDICATOR)
            .put("wither", Entity.WITHER)
            .put("ender_dragon", Entity.ENDER_DRAGON)
            .put("shulker", Entity.SHULKER)
            .put("endermite", Entity.ENDERMITE)
            .put("minecart", Entity.MINECART)
            .put("hopper_minecart", Entity.HOPPER_MINECART)
            .put("tnt_minecart", Entity.TNT_MINECART)
            .put("chest_minecart", Entity.CHEST_MINECART)
            .put("command_block_minecart", Entity.COMMAND_BLOCK_MINECART)
            .put("armor_stand", Entity.ARMOR_STAND)
            .put("item", Entity.ITEM)
            .put("tnt", Entity.TNT)
            .put("falling_block", Entity.FALLING_BLOCK)
            .put("xp_bottle", Entity.XP_BOTTLE)
            .put("xp_orb", Entity.XP_ORB)
            .put("eye_of_ender_signal", Entity.EYE_OF_ENDER_SIGNAL)
            .put("ender_crystal", Entity.ENDER_CRYSTAL)
            .put("shulker_bullet", Entity.SHULKER_BULLET)
            .put("fishing_hook", Entity.FISHING_HOOK)
            .put("dragon_fireball", Entity.DRAGON_FIREBALL)
            .put("arrow", Entity.ARROW)
            .put("snowball", Entity.SNOWBALL)
            .put("egg", Entity.EGG)
            .put("painting", Entity.PAINTING)
            .put("thrown_trident", Entity.THROWN_TRIDENT)
            .put("fireball", Entity.FIREBALL)
            .put("splash_potion", Entity.SPLASH_POTION)
            .put("ender_pearl", Entity.ENDER_PEARL)
            .put("leash_knot", Entity.LEASH_KNOT)
            .put("wither_skull", Entity.WITHER_SKULL)
            .put("wither_skull_dangerous", Entity.WITHER_SKULL_DANGEROUS)
            .put("boat", Entity.BOAT)
            .put("lightning_bolt", Entity.LIGHTNING_BOLT)
            .put("small_fireball", Entity.SMALL_FIREBALL)
            .put("llama_spit", Entity.LLAMA_SPIT)
            .put("area_effect_cloud", Entity.AREA_EFFECT_CLOUD)
            .put("lingering_potion", Entity.LINGERING_POTION)
            .put("fireworks_rocket", Entity.FIREWORKS_ROCKET)
            .put("evocation_fang", Entity.EVOCATION_FANG)
            .put("evocation_illager", Entity.EVOCATION_ILLAGER)
            .put("vex", Entity.VEX)
            .put("agent", Entity.AGENT)
            .put("ice_bomb", Entity.ICE_BOMB)
            .put("phantom", Entity.PHANTOM)
            .put("tripod_camera", Entity.TRIPOD_CAMERA)
            .build();

    /*private static final ImmutableBiMap<String, Integer> PARTICLE_IDENTIFIER = ImmutableBiMap.<String, Integer>builder()
            //TODO
            .put("bubble_column_up_particle", Particle.TYPE_BUBBLE_COLUMN_UP)
            .put("bubble_column_down_particle", Particle.TYPE_BUBBLE_COLUMN_DOWN)
            .build();*/

    public static ImmutableBiMap<String, Integer> getBlockIdentifier() {
        return BLOCK_IDENTIFIER;
    }

    public static ImmutableBiMap<String, Integer> getItemIdentifier() {
        return ITEM_IDENTIFIER;
    }

    public static ImmutableBiMap<String, Integer> getEntityIdentifier() {
        return ENTITY_IDENTIFIER;
    }

    /*public static ImmutableBiMap<String, Integer> getParticleIdentifier() {
        return PARTICLE_IDENTIFIER;
    }*/

    public static int toItemId(String identifier) {
        return toItemId(identifier, true);
    }

    public static int toItemId(String identifier, boolean prefix) {
        if (prefix) {
            identifier = identifier.replace(PREFIX, "");
        }
        Integer id = ITEM_IDENTIFIER.get(identifier);
        return id != null ? id : Item.AIR;
    }

    public static String itemIdToIdentifier(int id) {
        return itemIdToIdentifier(id, true);
    }

    public static String itemIdToIdentifier(int id, boolean prefix) {
        String identifier = ITEM_IDENTIFIER.inverse().get(id);
        return prefix ? PREFIX + identifier : identifier;
    }

    public static Item toItem(String identifier) {
        return toItem(identifier, true);
    }

    public static Item toItem(String identifier, boolean prefix) {
        return Item.get(toItemId(identifier, prefix));
    }

    public static String toIdentifier(Item item) {
        return toIdentifier(item, true);
    }

    public static String toIdentifier(Item item, boolean prefix) {
        return itemIdToIdentifier(item.getId(), prefix);
    }

    public static int toBlockId(String identifier) {
        return toBlockId(identifier, true);
    }

    public static int toBlockId(String identifier, boolean prefix) {
        if (prefix) {
            identifier = identifier.replace(PREFIX, "");
        }
        Integer id = BLOCK_IDENTIFIER.get(identifier);
        return id != null ? id : Block.AIR;
    }

    public static String blockIdToIdentifier(int id) {
        return blockIdToIdentifier(id, true);
    }

    public static String blockIdToIdentifier(int id, boolean prefix) {
        String identifier = BLOCK_IDENTIFIER.inverse().get(id);
        return prefix ? PREFIX + identifier : identifier;
    }

    public static Block toBlock(String identifier) {
        return toBlock(identifier, true);
    }

    public static Block toBlock(String identifier, boolean prefix) {
        return Block.get(toBlockId(identifier, prefix));
    }

    public static String toIdentifier(Block block) {
        return toIdentifier(block, true);
    }

    public static String toIdentifier(Block block, boolean prefix) {
        return blockIdToIdentifier(block.getId(), prefix);
    }

    public static int toEntityId(String identifier) {
        return toEntityId(identifier, true);
    }

    public static int toEntityId(String identifier, boolean prefix) {
        if (prefix) {
            identifier = identifier.replace(PREFIX, "");
        }
        Integer id = ENTITY_IDENTIFIER.get(identifier);
        return id != null ? id : -1;
    }

    public static String entityIdToIdentifier(int id) {
        return entityIdToIdentifier(id, true);
    }

    public static String entityIdToIdentifier(int id, boolean prefix) {
        String identifier = ENTITY_IDENTIFIER.inverse().get(id);
        return prefix ? PREFIX + identifier : identifier;
    }

    /*public static int toParticleId(String identifier) {
        return toParticleId(identifier, true);
    }

    public static int toParticleId(String identifier, boolean prefix) {
        if (prefix) {
            identifier = identifier.replace(PREFIX, "");
        }
        Integer id = PARTICLE_IDENTIFIER.get(identifier);
        return id != null ? id : -1;
    }

    public static String particleIdToIdentifier(int id) {
        return particleIdToIdentifier(id, true);
    }

    public static String particleIdToIdentifier(int id, boolean prefix) {
        String identifier = PARTICLE_IDENTIFIER.inverse().get(id);
        return prefix ? PREFIX + identifier : identifier;
    }*/
}
