package cn.nukkit.entity;

public interface EntityID {

    int CHICKEN = 10;
    int COW = 11;
    int PIG = 12;
    int SHEEP = 13;
    int WOLF = 14;
    int VILLAGER = 15;
    int MOOSHROOM = 16;
    int SQUID = 17;
    int RABBIT = 18;
    int BAT = 19;
    int IRON_GOLEM = 20;
    int SNOW_GOLEM = 21;
    int OCELOT = 22;
    int HORSE = 23;
    int DONKEY = 24;
    int MULE = 25;
    int SKELETON_HORSE = 26;
    int ZOMBIE_HORSE = 27;
    int POLAR_BEAR = 28;
    int LLAMA = 29;
    int PARROT = 30;
    int DOLPHIN = 31;
    int ZOMBIE = 32;
    int CREEPER = 33;
    int SKELETON = 34;
    int SPIDER = 35;
    int ZOMBIE_PIGMAN = 36;
    int SLIME = 37;
    int ENDERMAN = 38;
    int SILVERFISH = 39;
    int CAVE_SPIDER = 40;
    int GHAST = 41;
    int MAGMA_CUBE = 42;
    int BLAZE = 43;
    int ZOMBIE_VILLAGER = 44;
    int WITCH = 45;
    int STRAY = 46;
    int HUSK = 47;
    int WITHER_SKELETON = 48;
    int GUARDIAN = 49;
    int ELDER_GUARDIAN = 50;
    int NPC = 51; //Edu
    int WITHER = 52;
    int ENDER_DRAGON = 53;
    int SHULKER = 54;
    int ENDERMITE = 55;
    int AGENT = 56; //Edu
    int VINDICATOR = 57;
    int PHANTOM = 58;

    int ARMOR_STAND = 61;
    int TRIPOD_CAMERA = 62; //Edu
    int PLAYER = 63;
    int ITEM = 64;
    int TNT = 65;
    int FALLING_BLOCK = 66;
    int MOVING_BLOCK = 67;
    int XP_BOTTLE = 68;
    int XP_ORB = 69;
    int EYE_OF_ENDER_SIGNAL = 70;
    int ENDER_CRYSTAL = 71;
    int FIREWORKS_ROCKET = 72;
    int THROWN_TRIDENT = 73;
    int TURTLE = 74;
    int CAT = 75;
    int SHULKER_BULLET = 76;
    int FISHING_HOOK = 77;
    int CHALKBOARD = 78; //Edu
    int DRAGON_FIREBALL = 79;
    int ARROW = 80;
    int SNOWBALL = 81;
    int EGG = 82;
    int PAINTING = 83;
    int MINECART = 84;
    int FIREBALL = 85;
    int SPLASH_POTION = 86;
    int ENDER_PEARL = 87;
    int LEASH_KNOT = 88;
    int WITHER_SKULL = 89;
    int BOAT = 90;
    int WITHER_SKULL_DANGEROUS = 91;
    int LIGHTNING_BOLT = 93;
    int SMALL_FIREBALL = 94;
    int AREA_EFFECT_CLOUD = 95;
    int HOPPER_MINECART = 96;
    int TNT_MINECART = 97;
    int CHEST_MINECART = 98;

    int COMMAND_BLOCK_MINECART = 100;
    int LINGERING_POTION = 101;
    int LLAMA_SPIT = 102;
    int EVOCATION_FANG = 103;
    int EVOCATION_ILLAGER = 104;
    int VEX = 105;
    int ICE_BOMB = 106; //Edu
    int BALLOON = 107; //Edu
    int PUFFERFISH = 108;
    int SALMON = 109;
    int DROWNED = 110;
    int TROPICALFISH = 111;
    int COD = 112;
    int PANDA = 113;
    int PILLAGER = 114;
}
